name: Deploy to Netcup

on:
  push:
    branches:
      - main
  workflow_dispatch: # Erlaubt manuelles Auslösen in GitHub Actions

concurrency:
  group: deploy-netcup
  cancel-in-progress: false

jobs:
  web-deploy:
    name: Deploy to Netcup Webhosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: httpdocs/website/
          protocol: ftps
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/.idea/**
            **/README.md
            **/.gitignore
